# This is a basic workflow to help you get started with Actions

name: Release
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Pull current branch to accept branch
        run: git pull origin ${{ github.head_ref }} 
      - name: Push changes to accept branch
        run: |
          git config --global user.email "jeroen.beunckens@credon.eu.example"
          git config --global user.name "Jeroen Beuncken Example"
          git commit -am "Pull changes from current branch"
          git push origin accept-branch
